#
###################################
# Site wide configuration
####################################
#
title: 0c34n
email:
description: A documentation of my journey in the IT industry
url: # the base hostname & protocol for your site
keywords: ["blog", "projects", "ctf"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Singapore
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ocean
  avatar: water.png
  job: Student
  bio: "Slightly overgrown"
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Oceankoh
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: 
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

collections:
  projects:
    output: true

# Google Analytics
google_analytics: UA-152895693-1
